"""Cycles Management

Revision ID: 30dcade7eaa7
Revises: f5cc1ec53264
Create Date: 2025-04-22 20:38:03.550315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30dcade7eaa7'
down_revision = 'f5cc1ec53264'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sprint_project_map', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_comment', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('status_updated', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('status_updated_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['status_updated_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sprint_project_map', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('status_updated_by')
        batch_op.drop_column('status_updated')
        batch_op.drop_column('status_comment')

    # ### end Alembic commands ###
