"""Transition requests to goals

Revision ID: 48cd7a2f6d3b
Revises: aea45f0e38eb
Create Date: 2025-04-11 14:29:58.887700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48cd7a2f6d3b'
down_revision = 'aea45f0e38eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.Column('requested_by', sa.TEXT(), nullable=False),
    sa.Column('details', sa.TEXT(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goal_created'), ['created'], unique=False)
        batch_op.create_index(batch_op.f('ix_goal_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.drop_index('ix_request_created')
        batch_op.drop_index('ix_request_user_id')

    op.drop_table('request')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created', sa.DATETIME(), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.Column('details', sa.TEXT(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('requested_by', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.create_index('ix_request_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_request_created', ['created'], unique=False)

    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goal_user_id'))
        batch_op.drop_index(batch_op.f('ix_goal_created'))

    op.drop_table('goal')
    # ### end Alembic commands ###
