"""add project ownership model

Revision ID: 62dc7f2c63c5
Revises: 320b92e735f6
Create Date: 2025-04-21 14:14:12.176169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62dc7f2c63c5'
down_revision = '320b92e735f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=False))
        batch_op.create_index(batch_op.f('ix_project_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_project_user_id'))
        batch_op.drop_column('is_public')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
