"""Sprint initialization v2

Revision ID: 63859e886b59
Revises: d22518e2819a
Create Date: 2025-04-08 21:01:33.334786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63859e886b59'
down_revision = 'd22518e2819a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sprint', schema=None) as batch_op:
        batch_op.alter_column('date_start',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)
        batch_op.alter_column('date_end',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sprint', schema=None) as batch_op:
        batch_op.alter_column('date_end',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('date_start',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
