"""Add changelog table

Revision ID: 8a650e412963
Revises: 87faf13967cf
Create Date: 2025-04-15 11:32:11.651406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a650e412963'
down_revision = '87faf13967cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('changelogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('change_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('changelogs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_changelogs_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('changelogs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_changelogs_timestamp'))

    op.drop_table('changelogs')
    # ### end Alembic commands ###
