"""Requests table updated

Revision ID: 9a0ee6def8a6
Revises: 2a30658546b8
Create Date: 2025-04-04 21:39:35.115497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a0ee6def8a6'
down_revision = '2a30658546b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requested_by', sa.TEXT(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.drop_column('requested_by')

    # ### end Alembic commands ###
