"""Remove booleans

Revision ID: aea45f0e38eb
Revises: 31c59dddd35c
Create Date: 2025-04-11 14:21:24.902753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aea45f0e38eb'
down_revision = '31c59dddd35c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('discussion')
        batch_op.drop_column('backlog')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('backlog', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('discussion', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
