"""Sprint initialization v3 allow nullable fields

Revision ID: b2ccfd758480
Revises: 63859e886b59
Create Date: 2025-04-08 21:13:33.159317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2ccfd758480'
down_revision = '63859e886b59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sprint', schema=None) as batch_op:
        batch_op.alter_column('goals',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sprint', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('goals',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
