"""Added boolean to projects 2

Revision ID: b4631e8a7f4c
Revises: 171b41416b68
Create Date: 2025-04-10 14:25:13.222025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4631e8a7f4c'
down_revision = '171b41416b68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_sprint')
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('backlog', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('discussion', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('discussion')
        batch_op.drop_column('backlog')

    op.create_table('_alembic_tmp_sprint',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created', sa.DATETIME(), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.Column('date_start', sa.DATE(), nullable=False),
    sa.Column('date_end', sa.DATE(), nullable=False),
    sa.Column('goals', sa.TEXT(), nullable=False),
    sa.Column('status', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
