"""Sprint initialization

Revision ID: d22518e2819a
Revises: 7de6113fcf6d
Create Date: 2025-04-08 20:40:36.439795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd22518e2819a'
down_revision = '7de6113fcf6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sprint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.Column('date_start', sa.DateTime(), nullable=False),
    sa.Column('date_end', sa.DateTime(), nullable=False),
    sa.Column('goals', sa.TEXT(), nullable=False),
    sa.Column('status', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sprint', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sprint_created'), ['created'], unique=False)
        batch_op.create_index(batch_op.f('ix_sprint_date_end'), ['date_end'], unique=False)
        batch_op.create_index(batch_op.f('ix_sprint_date_start'), ['date_start'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sprint', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sprint_date_start'))
        batch_op.drop_index(batch_op.f('ix_sprint_date_end'))
        batch_op.drop_index(batch_op.f('ix_sprint_created'))

    op.drop_table('sprint')
    # ### end Alembic commands ###
