"""Added boolean to projects

Revision ID: 171b41416b68
Revises: b2ccfd758480
Create Date: 2025-04-10 14:22:25.717394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '171b41416b68'
down_revision = 'b2ccfd758480'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('backlog', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('discussion', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('discussion')
        batch_op.drop_column('backlog')

    # ### end Alembic commands ###
