"""Table updates for type and critical

Revision ID: 7c2fb87fefe6
Revises: c8809372ebc1
Create Date: 2025-04-13 21:55:43.023665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c2fb87fefe6'
down_revision = 'c8809372ebc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.DateTime(), nullable=True))

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.TEXT(), nullable=False))

    with op.batch_alter_table('sprint_project_map', schema=None) as batch_op:
        batch_op.add_column(sa.Column('critical', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sprint_project_map', schema=None) as batch_op:
        batch_op.drop_column('critical')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('type')

    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.drop_column('completed')

    # ### end Alembic commands ###
