version: '3'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=${SECRET_KEY:-yoursecretkeyhere}
      - DATABASE_URL=sqlite:////data/app.db
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_EMAIL=${ADMIN_EMAIL:-admin@example.com}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-change_me_immediately}
      - GUNICORN_WORKERS=3
      - HOST=0.0.0.0
      - PORT=5000
    volumes:
      - app_data:/data
    restart: unless-stopped

volumes:
  app_data:
    driver: local