"""add project ownership model v5

Revision ID: 6071b41ecc33
Revises: 138e0be60516
Create Date: 2025-04-21 14:55:11.072765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6071b41ecc33'
down_revision = '138e0be60516'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_project')
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index('ix_post_created')
        batch_op.drop_index('ix_post_user_id')

    op.drop_table('post')
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=False))
        batch_op.create_index(batch_op.f('ix_project_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_project_user_id', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_constraint('fk_project_user_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_project_user_id'))
        batch_op.drop_column('is_public')
        batch_op.drop_column('user_id')

    op.create_table('post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('created', sa.DATETIME(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_index('ix_post_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_post_created', ['created'], unique=False)

    op.create_table('_alembic_tmp_project',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('created', sa.DATETIME(), nullable=False),
    sa.Column('dri', sa.TEXT(), nullable=False),
    sa.Column('team', sa.TEXT(), nullable=False),
    sa.Column('context', sa.TEXT(), nullable=False),
    sa.Column('why', sa.TEXT(), nullable=False),
    sa.Column('requirements', sa.TEXT(), nullable=False),
    sa.Column('launch', sa.TEXT(), nullable=False),
    sa.Column('location', sa.TEXT(), nullable=True),
    sa.Column('type', sa.TEXT(), nullable=True),
    sa.Column('status', sa.TEXT(), nullable=True),
    sa.Column('objective_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('is_public', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['objective_id'], ['goal.id'], name='fk_project_goal'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_project_user_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###
