"""Requests table updated fix

Revision ID: 7de6113fcf6d
Revises: 9a0ee6def8a6
Create Date: 2025-04-04 21:47:58.856353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7de6113fcf6d'
down_revision = '9a0ee6def8a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        # If you're trying to drop a foreign key constraint, name it
        batch_op.drop_constraint('fk_request_some_column', type_='foreignkey')
        
        # Or if you're trying to drop a unique constraint
        batch_op.drop_constraint('uq_request_some_column', type_='unique')
        
        # Or if you're trying to drop a check constraint
        batch_op.drop_constraint('ck_request_some_column', type_='check')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_index('ix_request_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###
