"""Add fk and relationship to projects and objectives

Revision ID: d865570148c7
Revises: b2385560976e
Create Date: 2025-04-18 21:13:12.644172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd865570148c7'
down_revision = 'b2385560976e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('objective_id', sa.Integer(), nullable=True))
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_project_goal', 'goal', ['objective_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('objective_id')

    # ### end Alembic commands ###
