"""Added sprint-projects map

Revision ID: efa21591c518
Revises: b4631e8a7f4c
Create Date: 2025-04-10 15:02:15.527052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efa21591c518'
down_revision = 'b4631e8a7f4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sprint_project_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('added', sa.DateTime(), nullable=False),
    sa.Column('sprint_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('goal', sa.TEXT(), nullable=True),
    sa.Column('status', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprint.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sprint_project_map', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sprint_project_map_added'), ['added'], unique=False)
        batch_op.create_index(batch_op.f('ix_sprint_project_map_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sprint_project_map_sprint_id'), ['sprint_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sprint_project_map', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sprint_project_map_sprint_id'))
        batch_op.drop_index(batch_op.f('ix_sprint_project_map_project_id'))
        batch_op.drop_index(batch_op.f('ix_sprint_project_map_added'))

    op.drop_table('sprint_project_map')
    # ### end Alembic commands ###
